-- 코드를 입력하세요
-- GENDER는 0(남자), 1여자
-- ONLINE_SALE 도일한 날짜, 회원ID, 상품 Id에 대해서는 하나만 존재


-- 년,월, 성별 별로, 삼품을 구매한 회원 수를 집계
WITH NOTNULL AS (
    SELECT *
    FROM USER_INFO
    WHERE GENDER IS NOT NULL
)


SELECT EXTRACT(YEAR FROM O.SALES_DATE) as YEAR, EXTRACT(MONTH FROM O.SALES_DATE) as MONTH, U.GENDER, count(DISTINCT U.USER_ID) as USERS
FROM NOTNULL U
JOIN ONLINE_SALE O
ON U.USER_ID = O.USER_ID
GROUP BY EXTRACT(YEAR FROM O.SALES_DATE), EXTRACT(MONTH FROM O.SALES_DATE), U.GENDER
order by YEAR, MONTH, GENDER