select BOARD_ID AS BOARD_ID, WRITER_ID as WRITER_ID, TITLE as TITLE, PRICE as PRICE,
case
    WHEN STATUS = 'SALE' THEN '판매중'
    WHEN STATUS = 'RESERVED' THEN '예약중'
    WHEN STATUS = 'DONE' THEN '거래완료'
end as STATUS
from USED_GOODS_BOARD
where CREATED_DATE = DATE '2022-10-05'
order by BOARD_ID desc
